// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "ab25a18e-bc34-41e2-98bd-e596dghhs0b0af663";

const char SSID[]               = "Harsha";    // Network SSID (name)
const char PASS[]               = "12345678";    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = "KZGEPKFE9CAYG2VYOPUM";    // Secret device password

void onMessageChange();
void onAirqualityChange();

String message;
CloudPercentage airquality;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(message, READWRITE, ON_CHANGE, onMessageChange);
  ArduinoCloud.addProperty(airquality, READWRITE, ON_CHANGE, onAirqualityChange);
 

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
